name: mighty_delivery
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # CONNECTIVITY
  url_launcher: ^6.1.2
  package_info_plus: ^1.4.2
  intl: ^0.17.0
  html: ^0.15.0
  http: ^0.13.4

  # STATE MANAGEMENT
  mobx: ^2.0.7+2
  flutter_mobx: ^2.0.6+1

  # Base
  nb_utils: ^4.5.2
  google_fonts: ^2.3.3
  animated_bottom_navigation_bar: ^0.3.3

  # TOOLS
  cupertino_icons: ^1.0.4
  lottie: ^1.3.0
  timeline_tile: ^2.0.0
  country_code_picker: ^2.0.2

  # Dotted Line
  dotted_line: ^3.1.0

  # Payment gateway
  flutter_stripe: ^3.0.0
  razorpay_flutter: ^1.3.0
  flutterwave_standard: ^1.0.3
  paytm: ^3.0.1
  flutter_braintree: ^2.3.1
  mercado_pago_mobile_checkout: ^0.1.1
  flutter_paytabs_bridge: ^2.2.7
  my_fatoorah: ^3.0.11

  # IMAGES
  image_picker: ^0.8.5+3
  file_picker: ^4.5.1
  cached_network_image: ^3.2.1
  syncfusion_flutter_signaturepad: ^20.1.56
  screenshot: ^1.2.3
  date_time_picker: ^2.1.0

  # MAP
  geolocator: ^8.2.1
  google_maps_flutter: ^2.1.5
  flutter_polyline_points: ^1.0.0

  # PUSH NOTIFICATION
  onesignal_flutter: ^3.3.0

  #OTP TEXTFIELD
  otp_text_field: ^1.1.3

  #FIREBASE
  firebase_crashlytics: ^2.8.0
  firebase_core: ^1.17.0
  firebase_auth: ^3.3.18
  firebase_storage: ^10.2.16
  firebase_database: ^9.0.14
  paginate_firestore: ^1.0.3+1
  cloud_firestore: ^3.1.15

  # PHOTO VIEW
  photo_view: ^0.13.0

  # DOWNLOAD INVOICE PDF
  pdf: ^3.8.0
  path_provider: ^2.0.10
  open_file: ^3.2.1
  printing: ^5.9.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  mobx_codegen: ^2.0.7

dependency_overrides:
  freezed_annotation: ^2.0.3

  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/flag/

